# Generated by Django 3.2.9 on 2021-12-06 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_skills_about_skills_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='desription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='desription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='skills_about',
            old_name='desription',
            new_name='description',
        ),
    ]
